name: Build and Push App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Backend
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/dev-starttech-backend:latest .
          docker push ${{ steps.login-ecr.outputs.registry }}/dev-starttech-backend:latest

      # Security Scanning (scan the image from ECR after push)
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ steps.login-ecr.outputs.registry }}/dev-starttech-backend:latest'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'